<?php

/******************************************************************************/
/******************************************************************************/

class BCBSCountry
{
	/**************************************************************************/

	function __construct()
	{
		$this->country=BCBSGlobalData::setGlobalData('country',array($this,'init'));
	}
	
	/**************************************************************************/

	function init()
	{
		$country=array
		(
			'AF'=>array(esc_html__('Afghanistan','boat-charter-booking-system')),
			'AX'=>array(esc_html__('Aland Islands','boat-charter-booking-system')),
			'AL'=>array(esc_html__('Albania','boat-charter-booking-system')),
			'DZ'=>array(esc_html__('Algeria','boat-charter-booking-system')),
			'AS'=>array(esc_html__('American Samoa','boat-charter-booking-system')),
			'AD'=>array(esc_html__('Andorra','boat-charter-booking-system')),
			'AO'=>array(esc_html__('Angola','boat-charter-booking-system')),
			'AI'=>array(esc_html__('Anguilla','boat-charter-booking-system')),
			'AQ'=>array(esc_html__('Antarctica','boat-charter-booking-system')),
			'AG'=>array(esc_html__('Antigua And Barbuda','boat-charter-booking-system')),
			'AR'=>array(esc_html__('Argentina','boat-charter-booking-system')),
			'AM'=>array(esc_html__('Armenia','boat-charter-booking-system')),
			'AW'=>array(esc_html__('Aruba','boat-charter-booking-system')),
			'AU'=>array(esc_html__('Australia','boat-charter-booking-system')),
			'AT'=>array(esc_html__('Austria','boat-charter-booking-system')),
			'AZ'=>array(esc_html__('Azerbaijan','boat-charter-booking-system')),
			'BS'=>array(esc_html__('Bahamas','boat-charter-booking-system')),
			'BH'=>array(esc_html__('Bahrain','boat-charter-booking-system')),
			'BD'=>array(esc_html__('Bangladesh','boat-charter-booking-system')),
			'BB'=>array(esc_html__('Barbados','boat-charter-booking-system')),
			'BY'=>array(esc_html__('Belarus','boat-charter-booking-system')),
			'BE'=>array(esc_html__('Belgium','boat-charter-booking-system')),
			'BZ'=>array(esc_html__('Belize','boat-charter-booking-system')),
			'BJ'=>array(esc_html__('Benin','boat-charter-booking-system')),
			'BM'=>array(esc_html__('Bermuda','boat-charter-booking-system')),
			'BT'=>array(esc_html__('Bhutan','boat-charter-booking-system')),
			'BO'=>array(esc_html__('Bolivia','boat-charter-booking-system')),
			'BA'=>array(esc_html__('Bosnia And Herzegovina','boat-charter-booking-system')),
			'BW'=>array(esc_html__('Botswana','boat-charter-booking-system')),
			'BV'=>array(esc_html__('Bouvet Island','boat-charter-booking-system')),
			'BR'=>array(esc_html__('Brazil','boat-charter-booking-system')),
			'IO'=>array(esc_html__('British Indian Ocean Territory','boat-charter-booking-system')),
			'BN'=>array(esc_html__('Brunei Darussalam','boat-charter-booking-system')),
			'BG'=>array(esc_html__('Bulgaria','boat-charter-booking-system')),
			'BF'=>array(esc_html__('Burkina Faso','boat-charter-booking-system')),
			'BI'=>array(esc_html__('Burundi','boat-charter-booking-system')),
			'KH'=>array(esc_html__('Cambodia','boat-charter-booking-system')),
			'CM'=>array(esc_html__('Cameroon','boat-charter-booking-system')),
			'CA'=>array(esc_html__('Canada','boat-charter-booking-system')),
			'CV'=>array(esc_html__('Cape Verde','boat-charter-booking-system')),
			'KY'=>array(esc_html__('Cayman Islands','boat-charter-booking-system')),
			'CF'=>array(esc_html__('Central African Republic','boat-charter-booking-system')),
			'TD'=>array(esc_html__('Chad','boat-charter-booking-system')),
			'CL'=>array(esc_html__('Chile','boat-charter-booking-system')),
			'CN'=>array(esc_html__('China','boat-charter-booking-system')),
			'CX'=>array(esc_html__('Christmas Island','boat-charter-booking-system')),
			'CC'=>array(esc_html__('Cocos (Keeling) Islands','boat-charter-booking-system')),
			'CO'=>array(esc_html__('Colombia','boat-charter-booking-system')),
			'KM'=>array(esc_html__('Comoros','boat-charter-booking-system')),
			'CG'=>array(esc_html__('Congo','boat-charter-booking-system')),
			'CD'=>array(esc_html__('Congo, Democratic Republic','boat-charter-booking-system')),
			'CK'=>array(esc_html__('Cook Islands','boat-charter-booking-system')),
			'CR'=>array(esc_html__('Costa Rica','boat-charter-booking-system')),
			'CI'=>array(esc_html__('Cote D\'Ivoire','boat-charter-booking-system')),
			'HR'=>array(esc_html__('Croatia','boat-charter-booking-system')),
			'CU'=>array(esc_html__('Cuba','boat-charter-booking-system')),
			'CW'=>array(esc_html__('Curaçao','boat-charter-booking-system')),
			'CY'=>array(esc_html__('Cyprus','boat-charter-booking-system')),
			'CZ'=>array(esc_html__('Czech Republic','boat-charter-booking-system')),
			'DK'=>array(esc_html__('Denmark','boat-charter-booking-system')),
			'DJ'=>array(esc_html__('Djibouti','boat-charter-booking-system')),
			'DM'=>array(esc_html__('Dominica','boat-charter-booking-system')),
			'DO'=>array(esc_html__('Dominican Republic','boat-charter-booking-system')),
			'EC'=>array(esc_html__('Ecuador','boat-charter-booking-system')),
			'EG'=>array(esc_html__('Egypt','boat-charter-booking-system')),
			'SV'=>array(esc_html__('El Salvador','boat-charter-booking-system')),
			'GQ'=>array(esc_html__('Equatorial Guinea','boat-charter-booking-system')),
			'ER'=>array(esc_html__('Eritrea','boat-charter-booking-system')),
			'EE'=>array(esc_html__('Estonia','boat-charter-booking-system')),
			'ET'=>array(esc_html__('Ethiopia','boat-charter-booking-system')),
			'FK'=>array(esc_html__('Falkland Islands (Malvinas)','boat-charter-booking-system')),
			'FO'=>array(esc_html__('Faroe Islands','boat-charter-booking-system')),
			'FJ'=>array(esc_html__('Fiji','boat-charter-booking-system')),
			'FI'=>array(esc_html__('Finland','boat-charter-booking-system')),
			'FR'=>array(esc_html__('France','boat-charter-booking-system')),
			'GF'=>array(esc_html__('French Guiana','boat-charter-booking-system')),
			'PF'=>array(esc_html__('French Polynesia','boat-charter-booking-system')),
			'TF'=>array(esc_html__('French Southern Territories','boat-charter-booking-system')),
			'GA'=>array(esc_html__('Gabon','boat-charter-booking-system')),
			'GM'=>array(esc_html__('Gambia','boat-charter-booking-system')),
			'GE'=>array(esc_html__('Georgia','boat-charter-booking-system')),
			'DE'=>array(esc_html__('Germany','boat-charter-booking-system')),
			'GH'=>array(esc_html__('Ghana','boat-charter-booking-system')),
			'GI'=>array(esc_html__('Gibraltar','boat-charter-booking-system')),
			'GR'=>array(esc_html__('Greece','boat-charter-booking-system')),
			'GL'=>array(esc_html__('Greenland','boat-charter-booking-system')),
			'GD'=>array(esc_html__('Grenada','boat-charter-booking-system')),
			'GP'=>array(esc_html__('Guadeloupe','boat-charter-booking-system')),
			'GU'=>array(esc_html__('Guam','boat-charter-booking-system')),
			'GT'=>array(esc_html__('Guatemala','boat-charter-booking-system')),
			'GG'=>array(esc_html__('Guernsey','boat-charter-booking-system')),
			'GN'=>array(esc_html__('Guinea','boat-charter-booking-system')),
			'GW'=>array(esc_html__('Guinea-Bissau','boat-charter-booking-system')),
			'GY'=>array(esc_html__('Guyana','boat-charter-booking-system')),
			'HT'=>array(esc_html__('Haiti','boat-charter-booking-system')),
			'HM'=>array(esc_html__('Heard Island & Mcdonald Islands','boat-charter-booking-system')),
			'VA'=>array(esc_html__('Holy See (Vatican City State)','boat-charter-booking-system')),
			'HN'=>array(esc_html__('Honduras','boat-charter-booking-system')),
			'HK'=>array(esc_html__('Hong Kong','boat-charter-booking-system')),
			'HU'=>array(esc_html__('Hungary','boat-charter-booking-system')),
			'IS'=>array(esc_html__('Iceland','boat-charter-booking-system')),
			'IN'=>array(esc_html__('India','boat-charter-booking-system')),
			'ID'=>array(esc_html__('Indonesia','boat-charter-booking-system')),
			'IR'=>array(esc_html__('Iran, Islamic Republic Of','boat-charter-booking-system')),
			'IQ'=>array(esc_html__('Iraq','boat-charter-booking-system')),
			'IE'=>array(esc_html__('Ireland','boat-charter-booking-system')),
			'IM'=>array(esc_html__('Isle Of Man','boat-charter-booking-system')),
			'IL'=>array(esc_html__('Israel','boat-charter-booking-system')),
			'IT'=>array(esc_html__('Italy','boat-charter-booking-system')),
			'JM'=>array(esc_html__('Jamaica','boat-charter-booking-system')),
			'JP'=>array(esc_html__('Japan','boat-charter-booking-system')),
			'JE'=>array(esc_html__('Jersey','boat-charter-booking-system')),
			'JO'=>array(esc_html__('Jordan','boat-charter-booking-system')),
			'KZ'=>array(esc_html__('Kazakhstan','boat-charter-booking-system')),
			'KE'=>array(esc_html__('Kenya','boat-charter-booking-system')),
			'KI'=>array(esc_html__('Kiribati','boat-charter-booking-system')),
			'KR'=>array(esc_html__('Korea','boat-charter-booking-system')),
			'KW'=>array(esc_html__('Kuwait','boat-charter-booking-system')),
			'KG'=>array(esc_html__('Kyrgyzstan','boat-charter-booking-system')),
			'LA'=>array(esc_html__('Lao People\'s Democratic Republic','boat-charter-booking-system')),
			'LV'=>array(esc_html__('Latvia','boat-charter-booking-system')),
			'LB'=>array(esc_html__('Lebanon','boat-charter-booking-system')),
			'LS'=>array(esc_html__('Lesotho','boat-charter-booking-system')),
			'LR'=>array(esc_html__('Liberia','boat-charter-booking-system')),
			'LY'=>array(esc_html__('Libyan Arab Jamahiriya','boat-charter-booking-system')),
			'LI'=>array(esc_html__('Liechtenstein','boat-charter-booking-system')),
			'LT'=>array(esc_html__('Lithuania','boat-charter-booking-system')),
			'LU'=>array(esc_html__('Luxembourg','boat-charter-booking-system')),
			'MO'=>array(esc_html__('Macao','boat-charter-booking-system')),
			'MK'=>array(esc_html__('Macedonia','boat-charter-booking-system')),
			'MG'=>array(esc_html__('Madagascar','boat-charter-booking-system')),
			'MW'=>array(esc_html__('Malawi','boat-charter-booking-system')),
			'MY'=>array(esc_html__('Malaysia','boat-charter-booking-system')),
			'MV'=>array(esc_html__('Maldives','boat-charter-booking-system')),
			'ML'=>array(esc_html__('Mali','boat-charter-booking-system')),
			'MT'=>array(esc_html__('Malta','boat-charter-booking-system')),
			'MH'=>array(esc_html__('Marshall Islands','boat-charter-booking-system')),
			'MQ'=>array(esc_html__('Martinique','boat-charter-booking-system')),
			'MR'=>array(esc_html__('Mauritania','boat-charter-booking-system')),
			'MU'=>array(esc_html__('Mauritius','boat-charter-booking-system')),
			'YT'=>array(esc_html__('Mayotte','boat-charter-booking-system')),
			'MX'=>array(esc_html__('Mexico','boat-charter-booking-system')),
			'FM'=>array(esc_html__('Micronesia, Federated States Of','boat-charter-booking-system')),
			'MD'=>array(esc_html__('Moldova','boat-charter-booking-system')),
			'MC'=>array(esc_html__('Monaco','boat-charter-booking-system')),
			'MN'=>array(esc_html__('Mongolia','boat-charter-booking-system')),
			'ME'=>array(esc_html__('Montenegro','boat-charter-booking-system')),
			'MS'=>array(esc_html__('Montserrat','boat-charter-booking-system')),
			'MA'=>array(esc_html__('Morocco','boat-charter-booking-system')),
			'MZ'=>array(esc_html__('Mozambique','boat-charter-booking-system')),
			'MM'=>array(esc_html__('Myanmar','boat-charter-booking-system')),
			'NA'=>array(esc_html__('Namibia','boat-charter-booking-system')),
			'NR'=>array(esc_html__('Nauru','boat-charter-booking-system')),
			'NP'=>array(esc_html__('Nepal','boat-charter-booking-system')),
			'NL'=>array(esc_html__('Netherlands','boat-charter-booking-system')),
			'NC'=>array(esc_html__('New Caledonia','boat-charter-booking-system')),
			'NZ'=>array(esc_html__('New Zealand','boat-charter-booking-system')),
			'NI'=>array(esc_html__('Nicaragua','boat-charter-booking-system')),
			'NE'=>array(esc_html__('Niger','boat-charter-booking-system')),
			'NG'=>array(esc_html__('Nigeria','boat-charter-booking-system')),
			'NU'=>array(esc_html__('Niue','boat-charter-booking-system')),
			'NF'=>array(esc_html__('Norfolk Island','boat-charter-booking-system')),
			'MP'=>array(esc_html__('Northern Mariana Islands','boat-charter-booking-system')),
			'NO'=>array(esc_html__('Norway','boat-charter-booking-system')),
			'OM'=>array(esc_html__('Oman','boat-charter-booking-system')),
			'PK'=>array(esc_html__('Pakistan','boat-charter-booking-system')),
			'PW'=>array(esc_html__('Palau','boat-charter-booking-system')),
			'PS'=>array(esc_html__('Palestinian Territory, Occupied','boat-charter-booking-system')),
			'PA'=>array(esc_html__('Panama','boat-charter-booking-system')),
			'PG'=>array(esc_html__('Papua New Guinea','boat-charter-booking-system')),
			'PY'=>array(esc_html__('Paraguay','boat-charter-booking-system')),
			'PE'=>array(esc_html__('Peru','boat-charter-booking-system')),
			'PH'=>array(esc_html__('Philippines','boat-charter-booking-system')),
			'PN'=>array(esc_html__('Pitcairn','boat-charter-booking-system')),
			'PL'=>array(esc_html__('Poland','boat-charter-booking-system')),
			'PT'=>array(esc_html__('Portugal','boat-charter-booking-system')),
			'PR'=>array(esc_html__('Puerto Rico','boat-charter-booking-system')),
			'QA'=>array(esc_html__('Qatar','boat-charter-booking-system')),
			'RE'=>array(esc_html__('Reunion','boat-charter-booking-system')),
			'RO'=>array(esc_html__('Romania','boat-charter-booking-system')),
			'RU'=>array(esc_html__('Russian Federation','boat-charter-booking-system')),
			'RW'=>array(esc_html__('Rwanda','boat-charter-booking-system')),
			'BL'=>array(esc_html__('Saint Barthelemy','boat-charter-booking-system')),
			'SH'=>array(esc_html__('Saint Helena','boat-charter-booking-system')),
			'KN'=>array(esc_html__('Saint Kitts And Nevis','boat-charter-booking-system')),
			'LC'=>array(esc_html__('Saint Lucia','boat-charter-booking-system')),
			'MF'=>array(esc_html__('Saint Martin','boat-charter-booking-system')),
			'PM'=>array(esc_html__('Saint Pierre And Miquelon','boat-charter-booking-system')),
			'VC'=>array(esc_html__('Saint Vincent And Grenadines','boat-charter-booking-system')),
			'WS'=>array(esc_html__('Samoa','boat-charter-booking-system')),
			'SM'=>array(esc_html__('San Marino','boat-charter-booking-system')),
			'ST'=>array(esc_html__('Sao Tome And Principe','boat-charter-booking-system')),
			'SA'=>array(esc_html__('Saudi Arabia','boat-charter-booking-system')),
			'SN'=>array(esc_html__('Senegal','boat-charter-booking-system')),
			'RS'=>array(esc_html__('Serbia','boat-charter-booking-system')),
			'SC'=>array(esc_html__('Seychelles','boat-charter-booking-system')),
			'SL'=>array(esc_html__('Sierra Leone','boat-charter-booking-system')),
			'SG'=>array(esc_html__('Singapore','boat-charter-booking-system')),
			'SK'=>array(esc_html__('Slovakia','boat-charter-booking-system')),
			'SI'=>array(esc_html__('Slovenia','boat-charter-booking-system')),
			'SB'=>array(esc_html__('Solomon Islands','boat-charter-booking-system')),
			'SO'=>array(esc_html__('Somalia','boat-charter-booking-system')),
			'ZA'=>array(esc_html__('South Africa','boat-charter-booking-system')),
			'GS'=>array(esc_html__('South Georgia And Sandwich Isl.','boat-charter-booking-system')),
			'ES'=>array(esc_html__('Spain','boat-charter-booking-system')),
			'LK'=>array(esc_html__('Sri Lanka','boat-charter-booking-system')),
			'SD'=>array(esc_html__('Sudan','boat-charter-booking-system')),
			'SR'=>array(esc_html__('Suriname','boat-charter-booking-system')),
			'SJ'=>array(esc_html__('Svalbard And Jan Mayen','boat-charter-booking-system')),
			'SZ'=>array(esc_html__('Swaziland','boat-charter-booking-system')),
			'SE'=>array(esc_html__('Sweden','boat-charter-booking-system')),
			'CH'=>array(esc_html__('Switzerland','boat-charter-booking-system')),
			'SY'=>array(esc_html__('Syrian Arab Republic','boat-charter-booking-system')),
			'TW'=>array(esc_html__('Taiwan','boat-charter-booking-system')),
			'TJ'=>array(esc_html__('Tajikistan','boat-charter-booking-system')),
			'TZ'=>array(esc_html__('Tanzania','boat-charter-booking-system')),
			'TH'=>array(esc_html__('Thailand','boat-charter-booking-system')),
			'TL'=>array(esc_html__('Timor-Leste','boat-charter-booking-system')),
			'TG'=>array(esc_html__('Togo','boat-charter-booking-system')),
			'TK'=>array(esc_html__('Tokelau','boat-charter-booking-system')),
			'TO'=>array(esc_html__('Tonga','boat-charter-booking-system')),
			'TT'=>array(esc_html__('Trinidad And Tobago','boat-charter-booking-system')),
			'TN'=>array(esc_html__('Tunisia','boat-charter-booking-system')),
			'TR'=>array(esc_html__('Turkey','boat-charter-booking-system')),
			'TM'=>array(esc_html__('Turkmenistan','boat-charter-booking-system')),
			'TC'=>array(esc_html__('Turks And Caicos Islands','boat-charter-booking-system')),
			'TV'=>array(esc_html__('Tuvalu','boat-charter-booking-system')),
			'UG'=>array(esc_html__('Uganda','boat-charter-booking-system')),
			'UA'=>array(esc_html__('Ukraine','boat-charter-booking-system')),
			'AE'=>array(esc_html__('United Arab Emirates','boat-charter-booking-system')),
			'GB'=>array(esc_html__('United Kingdom','boat-charter-booking-system')),
			'US'=>array(esc_html__('United States','boat-charter-booking-system')),
			'UM'=>array(esc_html__('United States Outlying Islands','boat-charter-booking-system')),
			'UY'=>array(esc_html__('Uruguay','boat-charter-booking-system')),
			'UZ'=>array(esc_html__('Uzbekistan','boat-charter-booking-system')),
			'VU'=>array(esc_html__('Vanuatu','boat-charter-booking-system')),
			'VE'=>array(esc_html__('Venezuela','boat-charter-booking-system')),
			'VN'=>array(esc_html__('Viet Nam','boat-charter-booking-system')),
			'VG'=>array(esc_html__('Virgin Islands, British','boat-charter-booking-system')),
			'VI'=>array(esc_html__('Virgin Islands, U.S.','boat-charter-booking-system')),
			'WF'=>array(esc_html__('Wallis And Futuna','boat-charter-booking-system')),
			'EH'=>array(esc_html__('Western Sahara','boat-charter-booking-system')),
			'YE'=>array(esc_html__('Yemen','boat-charter-booking-system')),
			'ZM'=>array(esc_html__('Zambia','boat-charter-booking-system')),
			'ZW'=>array(esc_html__('Zimbabwe','boat-charter-booking-system'))
		);
		
		return($country);
	}
	
	/**************************************************************************/
	
	function getCountry($country=null)
	{
		if(is_null($country)) return($this->country);
		else return($this->country[$country]);
	}
	
	/**************************************************************************/
	
	function isCountry($index)
	{
		return(array_key_exists($index,$this->country));
	}
	
	/**************************************************************************/
	
	function getCountryName($index)
	{
		return($this->country[$index][0]);
	}
	
	/**************************************************************************/
}

/******************************************************************************/
/******************************************************************************/